// Cada tema é um conjunto de CSS Variables + uma "marca" (emoji + tagline) e,
// opcionalmente, um fundo (backdrop real do TMDB). Mesmo padrão do projeto
// Controle Financeiro: adicionar tema = adicionar uma entrada aqui.
//
// Os temas de dorama usam o backdrop OFICIAL vindo do TMDB como cena de fundo,
// com um véu na cor do tema pra manter o texto legível.
//
// Contrato de variáveis (as mesmas usadas em styles.css):
//   --cor-fundo, --cor-superficie, --cor-superficie-2, --cor-texto,
//   --cor-texto-suave, --cor-primaria, --cor-primaria-texto, --cor-secundaria,
//   --cor-borda, --fonte-base

const TMDB_BACKDROP = "https://image.tmdb.org/t/p/w780";

export const temas = [
  // ---------------- Lisos (sem fundo de dorama) ----------------
  {
    id: "rosa-fofo",
    nome: "Rosa Fofo",
    categoria: "Lisos",
    descricao: "Claro, rosa e lilás, bem fofo",
    amostra: { fundo: "#fff6fb", destaque: "#df4f94" },
    marca: { emoji: "💕", tagline: "Sua watchlist, seus surtos e suas doramigas." },
    variaveis: {
      "--cor-fundo": "#fff6fb",
      "--cor-superficie": "#ffffff",
      "--cor-superficie-2": "#fff0f7",
      "--cor-texto": "#2f1632",
      "--cor-texto-suave": "#7d647f",
      "--cor-primaria": "#df4f94",
      "--cor-primaria-texto": "#ffffff",
      "--cor-secundaria": "#8a5cf6",
      "--cor-borda": "#efd7e8",
      "--fonte-base": 'Inter, system-ui, -apple-system, "Segoe UI", sans-serif',
    },
  },
  {
    id: "roxo-cinema",
    nome: "Roxo Cinema",
    categoria: "Lisos",
    descricao: "Escuro, clima streaming",
    amostra: { fundo: "#140f1f", destaque: "#c084fc" },
    marca: { emoji: "🌙", tagline: "Modo maratona ativado." },
    variaveis: {
      "--cor-fundo": "#140f1f",
      "--cor-superficie": "#1d1730",
      "--cor-superficie-2": "#251d3d",
      "--cor-texto": "#f3eeff",
      "--cor-texto-suave": "#b3a6cf",
      "--cor-primaria": "#c084fc",
      "--cor-primaria-texto": "#1a1030",
      "--cor-secundaria": "#f472b6",
      "--cor-borda": "#322a4d",
      "--fonte-base": 'Inter, system-ui, -apple-system, "Segoe UI", sans-serif',
    },
  },
  {
    id: "pastel-doce",
    nome: "Pastel Doce",
    categoria: "Lisos",
    descricao: "Calmo, claro e amigável",
    amostra: { fundo: "#fdf4ff", destaque: "#fb7185" },
    marca: { emoji: "🍮", tagline: "Romance fofo sem susto." },
    variaveis: {
      "--cor-fundo": "#fdf4ff",
      "--cor-superficie": "#ffffff",
      "--cor-superficie-2": "#faf0ff",
      "--cor-texto": "#3b2a4a",
      "--cor-texto-suave": "#8b7a96",
      "--cor-primaria": "#fb7185",
      "--cor-primaria-texto": "#ffffff",
      "--cor-secundaria": "#a78bfa",
      "--cor-borda": "#f0e2f7",
      "--fonte-base": '"Trebuchet MS", Inter, system-ui, sans-serif',
    },
  },

  // ---------------- Doramas (fundo real do TMDB) ----------------
  {
    id: "rainha-das-lagrimas",
    nome: "Rainha das Lágrimas",
    categoria: "Doramas",
    descricao: "Azul-noite e prata, drama de chorar",
    tmdbId: 215720,
    backdrop: TMDB_BACKDROP + "/wcP3FsRLog4GNEs9PFrDKKQdcof.jpg",
    amostra: { fundo: "#0c1424", destaque: "#7aa2ff" },
    marca: { emoji: "😭", tagline: "Me destruiu, mas eu amei cada segundo." },
    variaveis: {
      "--cor-fundo": "#0c1424",
      "--cor-superficie": "#141d33",
      "--cor-superficie-2": "#1b2640",
      "--cor-texto": "#eaf0ff",
      "--cor-texto-suave": "#9fb0d0",
      "--cor-primaria": "#7aa2ff",
      "--cor-primaria-texto": "#0c1424",
      "--cor-secundaria": "#c0a3ff",
      "--cor-borda": "#26314e",
      "--fonte-base": '"Playfair Display", Georgia, serif',
    },
  },
  {
    id: "pousando-no-amor",
    nome: "Pousando no Amor",
    categoria: "Doramas",
    descricao: "Neve, creme e romance",
    tmdbId: 94796,
    backdrop: TMDB_BACKDROP + "/3yEHM2HT2vrUtO93YzTJNgEfiZG.jpg",
    amostra: { fundo: "#0e1726", destaque: "#8fd0ff" },
    marca: { emoji: "☂️", tagline: "O destino aterrissou bem aqui." },
    variaveis: {
      "--cor-fundo": "#0e1726",
      "--cor-superficie": "#162033",
      "--cor-superficie-2": "#1c2940",
      "--cor-texto": "#eef3fb",
      "--cor-texto-suave": "#a8bbd2",
      "--cor-primaria": "#8fd0ff",
      "--cor-primaria-texto": "#0e1726",
      "--cor-secundaria": "#f7b3c6",
      "--cor-borda": "#26344c",
      "--fonte-base": '"Playfair Display", Georgia, serif',
    },
  },
  {
    id: "vincenzo",
    nome: "Vincenzo",
    categoria: "Doramas",
    descricao: "Preto e dourado, vingança com estilo",
    tmdbId: 117376,
    backdrop: TMDB_BACKDROP + "/sf7NCqyVUNoyjYuwW5oJke1T1lH.jpg",
    amostra: { fundo: "#0c0c0f", destaque: "#d4af37" },
    marca: { emoji: "🕶️", tagline: "Elegância, fogo e zero piedade." },
    variaveis: {
      "--cor-fundo": "#0c0c0f",
      "--cor-superficie": "#16161b",
      "--cor-superficie-2": "#1e1e25",
      "--cor-texto": "#f5f0e6",
      "--cor-texto-suave": "#b6ab8e",
      "--cor-primaria": "#d4af37",
      "--cor-primaria-texto": "#0c0c0f",
      "--cor-secundaria": "#c0392b",
      "--cor-borda": "#2a2a31",
      "--fonte-base": '"Playfair Display", Georgia, serif',
    },
  },
  {
    id: "advogada-extraordinaria",
    nome: "Advogada Extraordinária",
    categoria: "Doramas",
    descricao: "Azul oceano e baleias",
    tmdbId: 197067,
    backdrop: TMDB_BACKDROP + "/tmgtlnBnoFvk52xZBO7Z0pTmN9b.jpg",
    amostra: { fundo: "#06283d", destaque: "#3fb6d3" },
    marca: { emoji: "🐋", tagline: "Meu nome é Woo, de Wonderful." },
    variaveis: {
      "--cor-fundo": "#06283d",
      "--cor-superficie": "#0c3450",
      "--cor-superficie-2": "#11405f",
      "--cor-texto": "#e6f6fb",
      "--cor-texto-suave": "#9cc4d6",
      "--cor-primaria": "#3fb6d3",
      "--cor-primaria-texto": "#06283d",
      "--cor-secundaria": "#7ee0c0",
      "--cor-borda": "#1a4a68",
      "--fonte-base": 'Inter, system-ui, -apple-system, sans-serif',
    },
  },
  {
    id: "pretendente-surpresa",
    nome: "Pretendente Surpresa",
    categoria: "Doramas",
    descricao: "Rosa rom-com, CEO e contrato",
    tmdbId: 154825,
    backdrop: TMDB_BACKDROP + "/lq0YqJuffMuZhoKTiC5xDqvtCSn.jpg",
    amostra: { fundo: "#1a0c18", destaque: "#ff6fae" },
    marca: { emoji: "💍", tagline: "Contrato falso, sentimento real." },
    variaveis: {
      "--cor-fundo": "#1a0c18",
      "--cor-superficie": "#261324",
      "--cor-superficie-2": "#311a2e",
      "--cor-texto": "#ffe9f5",
      "--cor-texto-suave": "#cf9fbe",
      "--cor-primaria": "#ff6fae",
      "--cor-primaria-texto": "#1a0c18",
      "--cor-secundaria": "#9b7cff",
      "--cor-borda": "#3a2236",
      "--fonte-base": 'Inter, system-ui, -apple-system, sans-serif',
    },
  },
  {
    id: "beleza-verdadeira",
    nome: "Beleza Verdadeira",
    categoria: "Doramas",
    descricao: "Escola, rosa e brilho",
    tmdbId: 112888,
    backdrop: TMDB_BACKDROP + "/3E1GroTJCRdIYHa5n62GqjmqxQR.jpg",
    amostra: { fundo: "#2a1022", destaque: "#ff7ec1" },
    marca: { emoji: "💄", tagline: "Triângulo amoroso e autoestima." },
    variaveis: {
      "--cor-fundo": "#2a1022",
      "--cor-superficie": "#371630",
      "--cor-superficie-2": "#431c3a",
      "--cor-texto": "#ffe8f4",
      "--cor-texto-suave": "#d7a4c4",
      "--cor-primaria": "#ff7ec1",
      "--cor-primaria-texto": "#2a1022",
      "--cor-secundaria": "#ffd166",
      "--cor-borda": "#4a2440",
      "--fonte-base": '"Trebuchet MS", Inter, system-ui, sans-serif',
    },
  },
  {
    id: "secretaria-kim",
    nome: "Secretária Kim",
    categoria: "Doramas",
    descricao: "Escritório chique, vinho e creme",
    tmdbId: 239993,
    backdrop: TMDB_BACKDROP + "/wvCF59w0fRTmPg3sJUxY3sf5p2C.jpg",
    amostra: { fundo: "#1b0f12", destaque: "#e0a96d" },
    marca: { emoji: "📎", tagline: "Por que será que ele é assim?" },
    variaveis: {
      "--cor-fundo": "#1b0f12",
      "--cor-superficie": "#28171b",
      "--cor-superficie-2": "#321d22",
      "--cor-texto": "#f6e9e0",
      "--cor-texto-suave": "#c4a596",
      "--cor-primaria": "#e0a96d",
      "--cor-primaria-texto": "#1b0f12",
      "--cor-secundaria": "#d98c9d",
      "--cor-borda": "#3a2329",
      "--fonte-base": '"Playfair Display", Georgia, serif',
    },
  },
];

export const temaPadrao = temas[0];

export function acharTema(id) {
  return temas.find((t) => t.id === id) || temaPadrao;
}

export const categorias = [...new Set(temas.map((t) => t.categoria))];
