-- Demonstração: migração publicada diretamente pelo Codex.
-- A tabela fica visível no Table Editor, mas não expõe dados pela API pública.

create table if not exists public.codex_sql_demo (
  id bigint generated by default as identity primary key,
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.codex_sql_demo enable row level security;

comment on table public.codex_sql_demo is
  'Tabela de demonstração criada por uma migração publicada diretamente pelo Codex.';

insert into public.codex_sql_demo (message)
select 'SQL publicado diretamente pelo Codex ✅'
where not exists (
  select 1
  from public.codex_sql_demo
  where message = 'SQL publicado diretamente pelo Codex ✅'
);
